import{
    gwen,
    gwenbday,
    gwencake,
    gwendecor,
    gwenfampose,
    gwenfamprayer,
    gwenmom,
    gwensceleb,
    gwensmile,  
    jud,
    judfamily,
    judfampenn,
    judfamstairs,
    judfullfam,
    judfullupenn,
    judnmom,
    judnpop,
    judpose,
    judstairs,
    levibaby,
    liawed,
    liawedsmile,
    psbday,
    pscake,
    psceleb,
    pscouple,
    elia,
    elia1,
    elia2,
    elia3,
    elia4,
    elia5,
    lia1,
    lia2,
    lia3,
    lia4,
    lia5,
    michael,
    michael1,
    michael2,
    michael3,
    michael4,
    michael5,
    michael6,
    jesslyn,
    jesslyn1,
    jesslyn2,
    jesslyn3,
    jesslyn4,
    jesslyn5,
    jesslyn6,
    satya,
    satya1,
    satya2,
    satya3,
    satya4,
    satya5,
    satya6,
    tina,
    tina1,
    tina2,
    tina3,
    tina4,
    tina5,
    tina6,
    tristan,
    tristan1,
    tristan2,
    tristan3,
    michael7,
    irvan,
    irvan1,
    irvan2,
    levibaby1,
} from '../img/portfolio/port'

const portfolioimg = [
    {
        category: "Graduation",
        id: 1,
        image: [judfamily,
        jud,
        judfampenn,
        judfamstairs,
        judfullfam,
        judfullupenn,
        judnmom,
        judnpop,
        judpose,
        judstairs,]
        
    },

    {
        category: "Birthday",
        id: 2,
        image: [psbday,
        pscake,
        psceleb,
        pscouple,
        gwen,
        gwenbday,
        gwencake,
        gwendecor,
        gwenfampose,
        gwenfamprayer,
        gwenmom,
        gwensceleb,
        gwensmile,
        jesslyn,
        jesslyn1,
        jesslyn2,
        jesslyn3,
        jesslyn4,
        jesslyn5,
        jesslyn6,
        satya,
        satya1,
        satya2,
        satya3,
        satya4,
        satya5,
        satya6,
        tina,
        tina1,
        tina2,
        tina3,
        tina4,
        tina5,
        tina6,
    ]

    },

    {
        category: "Wedding",
        id: 3,
        image: [liawed,
        liawedsmile,
        lia1,
        lia2,
        lia3,
        lia4,
        lia5,
        elia,
        elia1,
        elia2,
        elia3,
        elia4,
        elia5,
        michael,
        michael1,
        michael2,
        michael3,
        michael4,
        michael5,
        michael6,
        michael7,
    ]
    },

    {
        category: "Maternity & Baby",
        id: 4,
        image: [levibaby,
            levibaby1,
            tristan,
            tristan1,
            tristan2,
            tristan3,
            irvan,
            irvan1,
            irvan2,
        ]


    }
]


export {portfolioimg};